# Terminal utils
brew "coreutils"
brew "moreutils"
brew "starship"
brew "ripgrep"
brew "lazygit"
brew "zoxide"
brew "zellij"
brew "cmake"
brew "xmake"
brew "tmux"
brew "make"
brew "less"
brew "stow"
brew "eza"
brew "fzf"
brew "jq"

# Window Management
cask "nikitabobko/tap/aerospace"

# Programming Languages
brew "uv"
brew "go"
brew "gcc"
brew "rust"
brew "node"
cask "mactex"
brew "raylib"
brew "openblas"
brew "armadillo"
brew "python@3.13"
# brew "zig", args: [ "HEAD" ]

# Terms
cask "wezterm"
cask "ghostty"
cask "warp"

# Browsers
cask "zen-browser"

# Editors/Git
cask "visual-studio-code"
cask "sublime-text"
cask "arduino-ide"
cask "mplabx-ide"
cask "github"
brew "neovim"
# brew "emacs"
cask "zed"
brew "gh"

# Fonts
cask "font-jetbrains-mono-nerd-font"
cask "font-fira-code-nerd-font"
cask "font-fira-mono-nerd-font"

# Misc
cask "microsoft-office"
cask "hp-easy-start"
cask "google-drive"
cask "epic-games"
cask "bitwarden"
cask "whatsapp"
cask "raycast"
cask "spotify"
cask "notion"
cask "shottr"
cask "steam"
brew "yazi"
brew "htop"
cask "zoom"
cask "ibkr"
brew "mpv"

