;;; init.el --- Generated by initweave on 2026-03-30  -*- lexical-binding: t; -*-

;; PERFORMANCE OPTIMIZATIONS
;; =============================================================================

;; Increase garbage collection threshold to 100MB for faster startup and fewer pauses
(setq gc-cons-threshold 100000000)

;; Temporarily disable file-name-handler-alist during startup to speed things up
(defvar default-file-name-handler-alist file-name-handler-alist)
(setq file-name-handler-alist nil)
(add-hook 'emacs-startup-hook
          (lambda ()
            (setq file-name-handler-alist default-file-name-handler-alist)
            ;; Return GC to a more sensible (but still high) 20MB
            (setq gc-cons-threshold 20000000)))

;; Increase the amount of data read from processes to 1MB (default is 4KB)
;; This is CRITICAL for vterm and lsp (eglot) performance.
(setq read-process-output-max (* 1024 1024))

;; =============================================================================

;; This file was generated by https://initweave.com
;; Edit it freely — re-generate any time to pick up new modules.

;;; use-package bootstrap

;;; Package management — MELPA + use-package

(require 'package)

(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
(package-initialize)

;; Refresh package list on first run if needed
(unless package-archive-contents
  (package-refresh-contents))

;; Bootstrap use-package
(unless (package-installed-p 'use-package)
  (package-install 'use-package))

(require 'use-package)


;;; Sensible defaults

;; Silence startup noise
(setq inhibit-startup-message t
      inhibit-startup-echo-area-message t
      initial-scratch-message nil)

;; Show cheatsheet on startup
(setq initial-buffer-choice (expand-file-name "cheatsheet.org" user-emacs-directory))

(blink-cursor-mode -1)

;; Clean up the UI
(menu-bar-mode -1)
(tool-bar-mode -1)
(scroll-bar-mode -1)
(tooltip-mode -1)

;; Relative line numbers everywhere
(setq-default display-line-numbers-type 'relative)
(global-display-line-numbers-mode 1)

;; Set font
(set-face-attribute 'default nil :family "Iosevka" :height 120)

;; Remember cursor position between sessions
(save-place-mode 1)

;; Keep a list of recently opened files
(recentf-mode 1)
(setq recentf-max-saved-items 50)

;; No backup or lock files cluttering the filesystem
(setq make-backup-files nil
      auto-save-default nil
      create-lockfiles nil)

;; Prefer UTF-8 everywhere
(set-language-environment "UTF-8")
(prefer-coding-system 'utf-8)

;; Short answers ("y" / "n" instead of "yes" / "no")
(setq use-short-answers t)

;; Follow symlinks to version-controlled files without asking
(setq vc-follow-symlinks t)

;; Single space after sentence-ending period
(setq sentence-end-double-space nil)

;; Show matching parens immediately
(show-paren-mode 1)
(setq show-paren-delay 0)

;; Automatically keep buffers in sync with disk
(global-auto-revert-mode 1)
(setq global-auto-revert-non-file-buffers t)

;; Smooth scrolling
(setq scroll-step 1
      scroll-margin 0
      scroll-conservatively 101
      scroll-preserve-screen-position t
      auto-window-vscroll nil)
(pixel-scroll-precision-mode 1)

;; Custom keybindings for line selection and commenting
(defun mark-current-line ()
  "Select the current line."
  (interactive)
  (end-of-line)
  (set-mark (line-beginning-position)))

(defun mark-word-at-point ()
  "Select the word at point."
  (interactive)
  (unless (looking-at "\\<")
    (backward-word))
  (set-mark (point))
  (forward-word))

(global-set-key (kbd "C-l") 'mark-current-line)
(global-set-key (kbd "M-m") 'mark-word-at-point)
(global-set-key (kbd "C-SPC") 'set-mark-command)
(global-set-key (kbd "M-SPC") 'set-mark-command)
(global-set-key (kbd "C-c C-c") 'comment-line)
(global-set-key (kbd "C-c C-m") 'compile)

;; Ensure C-m is newline in GUI (it's the default in terminal)
(unless (display-graphic-p)
  (global-set-key (kbd "C-m") 'newline))
(when (display-graphic-p)
  (global-set-key (kbd "C-m") 'newline))


;;; Doom themes

(use-package doom-themes
  :ensure t
  :config
  ;; Global settings (optional)
  (setq doom-themes-enable-bold t    ; if nil, bold is universally disabled
        doom-themes-enable-italic t) ; if nil, italics is universally disabled

  ;; Add themes directory to the theme load path
  (add-to-list 'custom-theme-load-path (expand-file-name "themes" user-emacs-directory))
  (load-theme 'doom-oxocarbon t)

  ;; Enable flashing mode-line on errors
  (doom-themes-visual-bell-config)
  ;; Enable custom neotree theme (if you use it)
  (doom-themes-neotree-config)
  ;; or for treemacs users
  (setq doom-themes-treemacs-theme "doom-atom") ; use "doom-colors" for less
  (doom-themes-treemacs-config)
  ;; Corrects (and improves) org-mode's native fontification.
  (doom-themes-org-config))


;;; which-key

;;; which-key — keybinding discovery

(use-package which-key
  :ensure t
  :config
  (setq which-key-idle-delay 0.5
        which-key-idle-secondary-delay 0.05)
  (which-key-mode))


;;; Vertico + Marginalia

;;; Completion — Vertico (UI) + Marginalia (annotations)

(use-package vertico
  :ensure t
  :init
  (vertico-mode)
  :config
  (setq vertico-cycle t)
  (savehist-mode 1)
  (add-to-list 'savehist-additional-variables 'vertico-history))

(use-package marginalia
  :ensure t
  :after vertico
  :config
  (marginalia-mode))

;; Orderless: space-separated completion components in any order
(use-package orderless
  :ensure t
  :config
  (setq completion-styles '(orderless basic)
        completion-category-overrides '((file (styles basic partial-completion)))))


;;; Magit

;;; Magit — Git interface

(use-package magit
  :ensure t
  :bind ("C-c g" . magit-status)
  :config
  (setq magit-display-buffer-function #'magit-display-buffer-same-window-except-diff-v1))


;;; Eglot (LSP)

;;; Eglot — Language Server Protocol client (built-in, Emacs 29+)

(use-package treesit-auto
  :ensure t
  :config
  (global-treesit-auto-mode))

(use-package eglot
  :ensure nil
  :hook
  ((python-mode     . (lambda () (when (executable-find "pylsp") (eglot-ensure))))
   (js-mode         . (lambda () (when (executable-find "typescript-language-server") (eglot-ensure))))
   (typescript-mode . (lambda () (when (executable-find "typescript-language-server") (eglot-ensure))))
   (rust-mode       . (lambda () (when (executable-find "rust-analyzer") (eglot-ensure))))
   (rust-ts-mode    . (lambda () (when (executable-find "rust-analyzer") (eglot-ensure))))
   (go-mode         . (lambda () (when (executable-find "gopls") (eglot-ensure))))
   (c-mode          . (lambda () (when (executable-find "clangd") (eglot-ensure))))
   (c++-mode        . (lambda () (when (executable-find "clangd") (eglot-ensure))))
   (c-ts-mode       . (lambda () (when (executable-find "clangd") (eglot-ensure))))
   (c++-ts-mode     . (lambda () (when (executable-find "clangd") (eglot-ensure)))))
  :config
  ;; Shut down the server when the last buffer for its project is closed
  (setq eglot-autoshutdown t)
  ;; Don't log server events unless debugging
  (setq eglot-events-buffer-size 0)

  ;; Ensure eldoc is snappy and shows all relevant info
  (setq eldoc-echo-area-use-multiline-p t
        eldoc-documentation-strategy 'eldoc-documentation-compose
        eldoc-idle-delay 0.1)

  ;; Enable automatic symbol highlighting at point
  (add-hook 'eglot-managed-mode-hook
            (lambda ()
              (add-hook 'post-command-hook #'eglot-highlight-symbol-at-point nil t))))


;;; Corfu (in-buffer completion)

;;; Corfu — in-buffer completion popup

(use-package corfu
  :ensure t
  :custom
  (corfu-auto t)           ; complete automatically
  (corfu-auto-delay 0.2)
  (corfu-cycle t)          ; wrap around candidate list
  (corfu-quit-no-match t)
  :init
  (global-corfu-mode)
  ;; Transfer completions to the minibuffer (for commands that use completing-read)
  (defun corfu-move-to-minibuffer ()
    (interactive)
    (let ((completion-extra-properties corfu--extra)
          completion-cycle-threshold completion-cycling)
      (apply #'consult-completion-in-region completion-in-region--data)))
  :bind (:map corfu-map ("M-m" . corfu-move-to-minibuffer)))


;;; Projectile

;;; Projectile — project navigation

(use-package projectile
  :ensure t
  :config
  (setq projectile-completion-system 'default
        projectile-sort-order 'recentf
        projectile-project-search-path '("~/Documents/GitHub" "~/Documents/Probe")
        projectile-switch-project-action #'projectile-find-file)
  (projectile-mode +1)
  :bind
  ("C-c C-f" . projectile-find-file)
  :bind-keymap
  ("C-c p" . projectile-command-map))


;;; Perspective

;;; Perspective — workspace management

(use-package perspective
  :ensure t
  :bind (("C-x x x" . persp-switch)
         ("C-x x k" . persp-kill)
         ("C-x b"   . persp-switch-to-buffer*))
  :custom
  (persp-mode-prefix-key (kbd "C-x x"))
  :init
  (persp-mode))

(use-package persp-projectile
  :ensure t
  :after (perspective projectile)
  :config
  ;; Override the default 'p' key in projectile map to use perspectives
  (define-key projectile-command-map (kbd "p") #'projectile-persp-switch-project)
  ;; Remap projectile-switch-project to the perspective-aware version
  (with-eval-after-load 'projectile
    (define-key projectile-mode-map [remap projectile-switch-project] #'projectile-persp-switch-project)))


;;; AUCTeX (LaTeX)

;;; AUCTeX — LaTeX editing

(use-package auctex
  :ensure t
  :hook
  ((LaTeX-mode . turn-on-reftex)
   (LaTeX-mode . LaTeX-math-mode)
   (LaTeX-mode . flyspell-mode))
  :config
  (setq TeX-auto-save t
        TeX-parse-self t
        TeX-PDF-mode t
        TeX-source-correlate-mode t
        TeX-source-correlate-start-server t)
  ;; Ask for master file on first open
  (setq-default TeX-master nil))


;;; Flyspell (spell checking)

;;; Flyspell — on-the-fly spell checking

;; Requires aspell or hunspell to be installed on your system.
;; On macOS: brew install aspell   On Ubuntu/Debian: apt install aspell

(use-package flyspell
  :ensure nil
  :hook
  ((text-mode . flyspell-mode)
   (org-mode  . flyspell-mode)
   (prog-mode . flyspell-prog-mode))  ; checks comments/strings in code
  :config
  (setq ispell-program-name (or (executable-find "aspell")
                                (executable-find "hunspell")
                                "aspell")
        ispell-extra-args '("--sug-mode=ultra" "--lang=en_GB")))


;;; Markdown mode

;;; Markdown mode

(use-package markdown-mode
  :ensure t
  :mode
  (("README\.md\'" . gfm-mode)   ; GitHub-Flavoured Markdown
   ("\.md\'"       . markdown-mode)
   ("\.markdown\'" . markdown-mode))
  :config
  ;; Use pandoc for preview if available
  (setq markdown-command (or (executable-find "pandoc") "markdown")
        markdown-fontify-code-blocks-natively t
        markdown-hide-urls t))


;;; Eat terminal

;; (use-package eat
;;   :ensure t
;;   :bind ("C-c t" . eat)
;;   :config
;;   ;; Enable integration with shell and eshell
;;   (add-hook 'eshell-load-hook #'eat-eshell-mode)
;;   (add-hook 'eshell-load-hook #'eat-eshell-visual-command-mode))
(use-package ghostel
  :ensure t
  :bind ("C-c t" . ghostel))


;;; AI Code Interface

(use-package ai-code-interface
  :vc (:url "https://github.com/tninja/ai-code-interface.el" :branch "main")
  :bind (("C-c a i" . ai-code-interface-task)
         ("C-c a e" . ai-code-interface-explain)
         ("C-c a c" . ai-code-interface-chat))
  :config
  ;; You can customize the backend here if needed, defaults to openapi/gpt-4o
  ;; (setq ai-code-interface-backend 'openai)
  )


;;; Rust support

(use-package rust-mode
  :ensure t
  :init
  (setq rust-format-on-save t)
  :config
  ;; Only switch to rust-ts-mode if the tree-sitter grammar is actually installed
  (when (and (fboundp 'treesit-ready-p)
             (treesit-ready-p 'rust t))
    (setq rust-mode-ts-support t)))

;;; Org-mode

(use-package org
  :ensure nil
  :bind
  (("C-c o a" . org-agenda)
   ("C-c o l" . org-store-link)
   ("C-c o c" . org-capture))
  :init
  ;; Directory where your .org files live
  (setq org-directory "~/org")
  :config
  (setq org-default-notes-file (expand-file-name "inbox.org" org-directory))

  ;; Include all .org files in the agenda
  (setq org-agenda-files (list org-directory))

  ;; TODO state workflow
  (setq org-todo-keywords
        '((sequence "TODO(t)" "IN-PROGRESS(i!)" "WAITING(w@)" "|" "DONE(d!)" "CANCELLED(c@)")))

  ;; Visual tweaks
  (setq org-startup-indented t
        org-hide-leading-stars t
        org-ellipsis " ▾"
        org-src-fontify-natively t
        org-src-tab-acts-natively t
        org-edit-src-content-indentation 0
        org-return-follows-link t)

  ;; Log timestamps when tasks are closed
  (setq org-log-done 'time
        org-log-into-drawer t)

  ;; Capture templates
  (setq org-capture-templates
        '(("t" "Task" entry
           (file+headline org-default-notes-file "Tasks")
           "* TODO %?\n  %U\n  %a"
           :empty-lines 1)

          ("n" "Note" entry
           (file+headline org-default-notes-file "Notes")
           "* %? :note:\n  %U\n  %a"
           :empty-lines 1)

          ("j" "Journal" entry
           (file+datetree (expand-file-name "journal.org" org-directory))
           "* %<%H:%M> %?\n"
           :empty-lines 0)))

  ;; Babel languages
  (org-babel-do-load-languages
   'org-babel-load-languages
   '((python . t)
     (emacs-lisp . t)))

  ;; Use python3 explicitly
  (setq org-babel-python-command "python3")

  ;; Skip the "do you want to execute this?" prompt for trusted files.
  (setq org-confirm-babel-evaluate nil))

;;; Deft (note search)

;;; Deft — fast note search

(use-package deft
  :ensure t
  :config
  (setq deft-extensions '("org" "md" "txt")
        deft-directory org-directory
        deft-recursive t
        deft-use-filter-string-for-filename t
        deft-default-extension "org")
  :bind ("C-c /" . deft))


;;; PDF Tools

;;; PDF Tools — native PDF viewer

;; Requires poppler: brew install poppler  /  apt install libpoppler-glib-dev

(use-package pdf-tools
  :ensure t
  :config
  (pdf-tools-install)
  (setq-default pdf-view-display-size 'fit-page)
  (setq pdf-view-resize-factor 1.1)
  (setq pdf-annot-activate-created-annotations t)
  :mode ("\.pdf\'" . pdf-view-mode)
  :bind (:map pdf-view-mode-map
         ("C-s" . isearch-forward)))


;;; Org-roam (linked notes)

;;; Org-roam — networked note-taking

(use-package org-roam
  :ensure t
  :custom
  (org-roam-directory (expand-file-name "roam" org-directory))
  (org-roam-completion-everywhere t)
  :bind
  (("C-c n l" . org-roam-buffer-toggle)
   ("C-c n f" . org-roam-node-find)
   ("C-c n i" . org-roam-node-insert)
   ("C-c n c" . org-roam-capture)
   ("C-c n j" . org-roam-dailies-capture-today))
  :config
  ;; Build the node cache on startup (fast after first run)
  (org-roam-setup))


;;; Multiple cursors

(use-package multiple-cursors
  :ensure t
  :bind (("C-." . mc/mark-next-like-this)
         ("C-," . mc/mark-previous-like-this)
         ("C-c C-." . mc/mark-all-like-this)
         ("C-S-c C-S-c" . mc/edit-lines)))


;;; Vundo (visual undo)

(use-package vundo
  :ensure t
  :bind ("C-x u" . vundo))


;;; Vjump (visual jump tree)

(add-to-list 'load-path (expand-file-name "lisp" user-emacs-directory))
(require 'vjump)
(vjump-mode 1)
(global-set-key (kbd "C-x j") #'vjump-visualize)
(global-set-key (kbd "C-o")   #'vjump-go-back)
(when (display-graphic-p)
  (global-set-key (kbd "C-i") #'vjump-go-forward))


;;; TRAMP (remote editing)

;;; TRAMP — Transparent Remote Access, Multiple Protocol (built-in)

(use-package tramp
  :ensure nil
  :config
  (setq tramp-default-method "ssh"
        ;; Cache credentials for the session
        password-cache-expiry nil
        ;; Store auto-saves locally to avoid slow remote writes
        tramp-auto-save-directory (expand-file-name "tramp-autosave" user-emacs-directory))
  ;; Speed up connections by using remote PATH directly
  (add-to-list 'tramp-remote-path 'tramp-own-remote-path))

;;; init.el ends here

(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(package-selected-packages nil)
 '(package-vc-selected-packages
   '((ai-code-interface :url
			"https://github.com/tninja/ai-code-interface.el"
			:branch "main"))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
