#!/bin/bash

# essh: open GUI Emacs via TRAMP on a remote host

if [ $# -eq 0 ]; then
  echo "Usage: essh [user@]hostname [-p port]"
  exit 1
fi

host="" port=""
while [[ $# -gt 0 ]]; do
  case $1 in
    -p) port="$2"; shift 2 ;;
    -*) shift ;;
    *)  [[ -z "$host" ]] && host="$1"; shift ;;
  esac
done

if [[ -z "$host" ]]; then
  echo "Error: no hostname"
  exit 1
fi

tramp_path="/ssh:$host:"
if [[ -n "$port" ]]; then
  if [[ "$host" == *"@"* ]]; then
    tramp_path="/ssh:${host%@*}@${host#*@}#$port:"
  else
    tramp_path="/ssh:$host#$port:"
  fi
fi

echo "Opening Emacs TRAMP: $tramp_path"
nohup emacs "$tramp_path" >/dev/null 2>&1 &
